### ISSUE TITLE
Error using Home Assistant 2025.5.3

### ISSUE THREAD

**Issue by llerda** [seven-io/home-assistant#7]
Dear, automation goes in error and service not found.

Configuration.yaml

     
notify:
  - platform: seven
    sender: HomeAssist # defaults to hass - see https://help.seven.io/en/set-sender-id
    name: "seven_sms"
    api_key: MY API KEY
    recipient: 00393357539667 # or specify multiple numbers e.g. [01771783130, 01716992343]
  - platform: seven
    sender: +491771783130 # - see https://help.seven.io/en/shared-numbers
    name: "seven_voice"
    api_key:  MY API KEY
    recipient: 00393357539667
    type: 'voice'

Automation
alias: New automation
description: ""
triggers: []
conditions: []
actions:
  - data:
      data:
        sender: From_Name
      message: "{{ states(\"sensor.sensor_name\") }}"
      target: MY PHONE NUMBER
    action: notify.seven_sms
mode: single

Error : 
Perform action 'notify.seven_sms'
Executed: June 1, 2025 at 12:54:18 AM
Error: Action notify.seven_sms not found

I cannot understand where is the error.

thanks

**Comment by matthiez** [comment]
HI @llerda 
sorry for the delay.

You need to restart HA after adding the actions to configuration.yaml and it should work just fine after that.

```
alias: New automation
description: ""
triggers: []
conditions: []
actions:
  - action: notify.seven_sms
    metadata: {}
    data:
      target: 491716992343
      message: test
mode: single
```
